swiftmailer:
    url: '%env(MAILER_URL)%'
    spool: { type: 'memory' }
    delivery_addresses: ['torkhan2706@gmail.com']
    transport: gmail
    auth_mode: login
    port: 465
    host: localhost
    username: 'torkhan2706@gmail.com'
    password: 'Coleengarou654!'
    encryption: ssl
    stream_options:
        ssl:
            allow_self_signed: true
            verify_peer: false
            verify_peer_name: false

